service: ton-challenge-access-api

frameworkVersion: '2'

variablesResolutionMode: 20210326
configValidationMode: error

plugins:
  - serverless-offline
  - serverless-mocha-plugin

custom:
  serverless-offline:
    httpPort: 3000
  serverless-mocha-plugin:
    preTestCommands: 
      - bash startOffline.sh
    postTestCommands:
      - bash stopOffline.sh

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  stage: dev
  environment:
    COUNT_KEY: test.ton.v1

functions:
  update:
    description: Stores the log details
    handler: api/controllers/update.handle
    events:
      - http:
          path: /access
          method: PUT
  get:
    description: Stores the log details
    handler: api/controllers/get.handle
    events:
      - http:
          path: /access
          method: GET
